{% set name = "dash-auth" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_auth-{{ version }}.tar.gz
  sha256: 72df43248c15e121f8d5d710981e880deb2df546b564f2951a10ca50d7d92f6d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - dash >=1.1.1
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - dash_auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://plotly.com/dash
  summary: Dash Authorization Package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
