{% set name = "dash-auth" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_auth-{{ version }}.tar.gz
  sha256: d9eafb8f3e1f1580bcf90023f8a5915f8f44ee07d80e35490b32f3548da49cc5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - chart-studio >=1.0.0
    - dash >=1.1.1
    - flask >=1.0.2
    - flask-compress
    - flask-seasurf
    - itsdangerous >=1.1.0
    - python
    - requests
    - retrying
    - ua-parser

test:
  imports:
    - dash_auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://plotly.com/dash
  summary: Dash Authorization Package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
