{% set name = "dash-auth" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_auth-{{ version }}.tar.gz
  sha256: 2841586ca79459d6dfabc3ed1837a71a9731118852e99ef2c2078976c61e6fb5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - dash >=1.1.1
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - dash_auth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://plotly.com/dash
  summary: Dash Authorization Package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
